### ISSUE TITLE
Deep learning for computer vision

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#166] opened 2023-04-25 18:35 UTC
Please cite the book by Adrian Rosebrock using a proper BibTeX entry

<img width="407" alt="image" src="https://user-images.githubusercontent.com/21175639/234370136-a00351f3-822f-4dc3-bdd5-b8e184dd128c.png">

Something like this should get you started:

```
@Book{citekey,
  author    = "",
  title     = "",
  publisher = "",
  year      = ""
}
```

https://github.com/openjournals/joss-reviews/issues/5027

**Comment by 5uperpalo** [comment] 2023-04-25 20:59
thank you for the comment, the issue is resolved in the latest version of the [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf).

![image](https://user-images.githubusercontent.com/36483359/234402226-31a19a43-c2fa-4d75-8c47-06fef430b3c9.png)

![image](https://user-images.githubusercontent.com/36483359/234402299-5224184f-a6b7-4184-818d-2da0a1b71eab.png)

**Closed by 5uperpalo** 2023-04-25 20:59 UTC
