### ISSUE TITLE
Fastai tokenizer

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#165] opened 2023-04-25 18:32 UTC
The citation to Fastai tokenizer is not very informative. I think this paper is a better reference to fastai: https://www.mdpi.com/2078-2489/11/2/108

<img width="506" alt="image" src="https://user-images.githubusercontent.com/21175639/234369486-4d403423-9658-4bee-9603-731fc675eb28.png">

https://github.com/openjournals/joss-reviews/issues/5027

**Comment by 5uperpalo** [comment] 2023-04-25 20:58
thank you for the comment, the issue is resolved in the latest version of the [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf).

![image](https://user-images.githubusercontent.com/36483359/234401981-c2b5fff7-a0f8-4a3d-bd32-c3bdb10f7ac6.png)

![image](https://user-images.githubusercontent.com/36483359/234402046-b879d50f-8fbf-40e2-aa65-4b46da11ba7b.png)

**Closed by 5uperpalo** 2023-04-25 20:58 UTC
