### ISSUE TITLE
Editorial comment

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#157] opened 2023-04-25 17:55 UTC
On line 36, please add a space between "Deep and Cross" and the parenthesized reference:

<img width="740" alt="image" src="https://user-images.githubusercontent.com/21175639/234361471-07b30b98-d6c0-4cd6-85c9-f432bf2e8801.png">

https://github.com/openjournals/joss-reviews/issues/5027

**Comment by 5uperpalo** [comment] 2023-04-25 20:46
thank you for the comment, the issue is resolved in the latest version of the [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf).
![image](https://user-images.githubusercontent.com/36483359/234399573-2dc6ec10-115a-4015-a66b-e80bcdf0d15e.png)

**Closed by 5uperpalo** 2023-04-25 20:46 UTC
