### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by twhelan22** [jrzaurin/pytorch-widedeep#85] opened 2022-03-24 09:11 UTC
This appears to be caused by opencv-contrib-python being installed as part of the requirements. I am running this on a cloud notebook and the machine I am working on already has opencv-python-headless installed, which is more appropriate for a cloud server environment. To resolve the error I have to update opencv-python-headless after installing pytorch-widedeep; however, the guidance [here](https://pypi.org/project/opencv-contrib-python/) states that installing multiple packages in the same environment isn't recommended:

`There are four different packages (see options 1, 2, 3 and 4 below) and you should SELECT ONLY ONE OF THEM. Do not install multiple different packages in the same environment. There is no plugin architecture: all the packages use the same namespace (cv2). If you installed multiple different packages in the same environment, uninstall them all with pip uninstall and reinstall only one package.`

![dbabb0ca75c7e33116e2434ddd25d426](https://user-images.githubusercontent.com/17239157/159882034-1c1eb232-e020-4770-99bf-f892b45dcd01.png)

**Comment by jrzaurin** [comment] 2022-03-24 09:39
Well, I would suggest to start a clean environment in your server, whether using conda, pyenv, poetry...whatever, and then install `pytorch-widedeep` in that clean environment.  That should fix the problem. 

Otherwise, I would say that the problem is related to some missing dependencies: https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo

Have a look and let me know if it works :)

**Comment by jrzaurin** [comment] 2022-04-15 13:35
@twhelan22 

are things ok? all working?

**Comment by jrzaurin** [comment] 2022-04-18 08:12
Closing this, will re-open if the issue is indeed related to the library

**Closed by jrzaurin** 2022-04-18 08:12 UTC
