### ISSUE TITLE
torchsample citation

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#164] opened 2023-04-25 18:28 UTC
Please provide at least a date and a url in the citation of `torchsample`. You could start with the BibTeX for torchvision in #163.

<img width="518" alt="image" src="https://user-images.githubusercontent.com/21175639/234368826-7c84792a-7616-427d-95a8-d0e07f2534a4.png">

<img width="518" alt="image" src="https://user-images.githubusercontent.com/21175639/234368837-c8d7b1c3-32a9-40bc-bb2e-be5872422c0b.png">

**Comment by 5uperpalo** [comment] 2023-04-25 20:57
thank you for the comment, the issue is resolved in the latest version of the [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf).

![image](https://user-images.githubusercontent.com/36483359/234401764-a8027b53-c714-4a15-a93b-8003d9061cbf.png)

![image](https://user-images.githubusercontent.com/36483359/234401644-5e6f4a55-5135-490c-9ac7-8e083ed2e281.png)

**Closed by 5uperpalo** 2023-04-25 20:57 UTC
