### ISSUE TITLE
TorchVision citations

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#163] opened 2023-04-25 18:24 UTC
Please remove the separate citations to TorchVision Models and TorchVision multi weight support, and instead cite TorchVision [as they request](https://pypi.org/project/torchvision/)

```
@software{torchvision2016,
    title        = {TorchVision: PyTorch's Computer Vision library},
    author       = {TorchVision maintainers and contributors},
    year         = 2016,
    journal      = {GitHub repository},
    publisher    = {GitHub},
    howpublished = {\url{https://github.com/pytorch/vision}}
}
```

<img width="683" alt="image" src="https://user-images.githubusercontent.com/21175639/234367789-56bace20-a1dd-46fd-bf56-97c0c1e550e5.png">

https://github.com/openjournals/joss-reviews/issues/5027

**Comment by 5uperpalo** [comment] 2023-04-25 20:55
thank you for the comment, the issue is resolved in the latest version of the [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf).

![image](https://user-images.githubusercontent.com/36483359/234401345-d08c2bda-7cdc-458a-8fa9-698dd6c21e8d.png)

![image](https://user-images.githubusercontent.com/36483359/234401430-6d6e059f-8a62-491a-b1b1-1965bf2029ee.png)

**Closed by 5uperpalo** 2023-04-25 20:55 UTC
