### ISSUE TITLE
Editorial comment

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#159] opened 2023-04-25 18:02 UTC
I suggest rewriting the highlighted text to "Following the notation of Cheng et al. (2016), ..."

<img width="945" alt="image" src="https://user-images.githubusercontent.com/21175639/234363210-829162c5-244a-47ed-8d87-97ce7cffa880.png">

https://github.com/openjournals/joss-reviews/issues/5027

**Comment by 5uperpalo** [comment] 2023-04-25 20:50
thank you for the comment, the issue is resolved in the latest version of the [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf).
![image](https://user-images.githubusercontent.com/36483359/234400510-6d0a9a2a-cbb0-46d9-948e-7205534d7b09.png)

**Closed by 5uperpalo** 2023-04-25 20:50 UTC
