### ISSUE TITLE
Editorial comment

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#158] opened 2023-04-25 17:57 UTC
Please add a small caption to Figure 1, briefly describing what it shows. 

You might want to move one or more sentences from the main text to the caption. Alternatively, you could simply write something like "Figure 1. Main components of the pytorch-widedeep architecture."

<img width="896" alt="image" src="https://user-images.githubusercontent.com/21175639/234361947-a21cd56e-c644-4f78-91f2-872db02a679d.png">

https://github.com/openjournals/joss-reviews/issues/5027

**Comment by 5uperpalo** [comment] 2023-04-25 20:47
thank you for the comment, the issue is resolved in the latest version of the [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf). I moved all relevant picture information into caption.
![image](https://user-images.githubusercontent.com/36483359/234399790-b6b69e5e-ac67-4a48-9f50-421e8c9212c6.png)

**Closed by 5uperpalo** 2023-04-25 20:47 UTC
