### ISSUE TITLE
Editorial comment

### ISSUE THREAD

**Issue by osorensen** [jrzaurin/pytorch-widedeep#161] opened 2023-04-25 18:14 UTC
Please remove "While" at the beginning of line 57, so it becomes "If there is a ...":

<img width="763" alt="image" src="https://user-images.githubusercontent.com/21175639/234365524-31ba2212-1b60-43c6-a071-7a6355e1b78e.png">

https://github.com/openjournals/joss-reviews/issues/5027

**Comment by 5uperpalo** [comment] 2023-04-25 20:52
thank you for the comment, the issue is resolved in the latest version of the [paper](https://raw.githubusercontent.com/openjournals/joss-papers/joss.05027/joss.05027/10.21105.joss.05027.pdf).
![image](https://user-images.githubusercontent.com/36483359/234400756-20a0edb9-5019-4487-bc66-0d2368ae141d.png)

**Closed by 5uperpalo** 2023-04-25 20:52 UTC
